### ISSUE TITLE
Service not recognising any tram stops

### ISSUE THREAD

**Issue by Doodlepaul** [wmcadigital/wmn-disruptions#640] opened 2022-08-05 14:58 UTC
The disruptions service doesn't seem to recognise any tram stop names.

See https://find-metro-zones.tfwm.org.uk/ for more info on stops...

![Screenshot 2022-08-05 at 15 57 02](https://user-images.githubusercontent.com/68856858/183103968-7249ece3-9066-48db-90fc-5c44983c0015.png)

**Comment by sudheer-rk** [comment] 2022-08-10 11:22
Looks like the staging api is returning empty array for metroStopSearch. Screenshot attached

![image](https://user-images.githubusercontent.com/92720228/183896796-cb1c1a8b-3dff-4d87-89cd-177e285b3c8e.png)

**Comment by sam-wmca** [comment] 2022-08-10 11:30
Thanks @sudheer-rk, do you know if its the same issue in the live API? https://api.wmnetwork.co.uk/Metro/v2/stop

**Comment by sudheer-rk** [comment] 2022-08-10 12:05
@sam-wmca, even live api returns empty array. 

![image](https://user-images.githubusercontent.com/92720228/183896628-898546fc-5bd0-43aa-bd9f-68d5b67ae2b5.png)

**Comment by sam-wmca** [comment] 2022-09-26 08:34
Duplicate of 655. Closed

**Closed as completed by sam-wmca** 2022-09-26 08:34 UTC
Labels: bug
